package com.maxclay.repository;

import com.maxclay.model.User;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * Since interface extends {@link org.springframework.data.mongodb.repository.MongoRepository}
 * implementation will be generated by Spring Data.
 *
 * @author Vlad Glinskiy
 */
public interface UserRepository extends MongoRepository<User, String> {
}
