package com.maxclay.repository;

import com.maxclay.model.Account;
import org.springframework.data.mongodb.repository.MongoRepository;

/**
 * Declares methods using domain-specific language (DSL) where persistence details are expressed in repository method
 * signatures. Since interface extends {@link org.springframework.data.mongodb.repository.MongoRepository}
 * implementation will be generated by Spring Data.
 *
 * @author Vlad Glinskiy
 */
public interface AccountRepository extends MongoRepository<Account, String> {

    Account findByEmail(String email);
}
